### ISSUE TITLE
Doesn't open in Adobe Reader

### ISSUE THREAD

**Issue by pablojimenezmateo** [pablojimenezmateo/curriculum-bootloader#4]
At the moment it does not open in Adobe Reader.

**Comment by RadicalEd360** [comment]
lmao, its not a pdf file, running the linux filetype scanning utility 'file' we see that its actually a bootloader:
`cv.pdf: DOS/MBR boot sector, code offset 0x3c+2, OEM-ID "mkfs.fat", root entries 22
7e5a1a, unlabeled, FAT (12 bit)`

**Comment by RadicalEd360** [comment]
well played sir

**Comment by RadicalEd360** [comment]
awesome job btw!

**Comment by pablojimenezmateo** [comment]
Fixed in the last commit!
